/**
 * Rewrites the harvested Brooks catalog into a synthetic one.
 *
 * Why this is a script and not a hand-edited JSON file: the catalog is 226
 * products and 821 colourways, and it is re-harvested (`bun run harvest`).
 * A one-time manual scrub would be undone by the next harvest and could not be
 * audited. Running the transform means the de-branded catalog is reproducible
 * and the diff of *what* was replaced lives in `names.js`.
 *
 * Usage: node tools/debrand/debrand.js
 * Reads  packages/catalog/catalog.json
 * Writes packages/catalog/catalog.json  (in place; commit the result)
 */

const fs = require('fs');
const path = require('path');

const { FRANCHISE, MARKS, GLOBAL_RENAMES } = require('./names.js');
const { swatchFor } = require('./swatch.js');
const { describe } = require('./copy.js');

const ROOT = path.resolve(__dirname, '../..');
const CATALOG = path.join(ROOT, 'packages/catalog/catalog.json');

/** Slug fragments in `groups` that name a Brooks franchise or partner. */
const GROUP_SLUGS = [
  ['brooks-running-shoes', 'demo-running-shoes'],
  ['brooks-running-apparel', 'demo-running-apparel'],
  ['featured-adrenaline-gts', 'featured-steadyline'],
  ['featured-addiction', 'featured-mainstay'],
  ['featured-cascadia', 'featured-ridgewalk'],
  ['featured-ghost', 'featured-halcyon'],
  ['featured-glycerin', 'featured-softfall'],
  ['featured-hyperion', 'featured-quickstep'],
  ['featured-launch', 'featured-liftoff'],
  ['featured-revel', 'featured-everyday'],
  // Third-party licensing deals have no place in a demo catalog.
  ['featured-rundisney', 'featured-themepark'],
  // Names the search vendor Brooks uses; irrelevant once search is local.
  ['featured-constructor-new', 'featured-index-new'],
  ['featured-constructor', 'featured-index'],
];

/** Apply the global renames and mark replacements to any free text. */
function demark(text) {
  if (!text) return text;
  let out = String(text);
  for (const [re, to] of GLOBAL_RENAMES) out = out.replace(re, to);
  for (const [re, to] of MARKS) out = out.replace(re, to);
  // The brand itself, and the possessive form its copy uses.
  out = out.replace(/Brooks['’]s/g, 'our').replace(/\bBrooks\b/g, 'Ecommerce Demo');
  return out.replace(/\s{2,}/g, ' ').trim();
}

/** Rename a product, swapping the franchise token and stripping marks. */
function renameProduct(name, franchise) {
  const to = FRANCHISE[franchise];
  let out = String(name);
  if (to && franchise) {
    // Word-boundary replace so "Run" inside "Running" survives untouched.
    const re = new RegExp(`\\b${franchise.replace(/[.*+?^${}()|[\]\\-]/g, '\\$&')}\\b`, 'g');
    out = out.replace(re, to);
  }
  return demark(out);
}

/**
 * Short attribute phrases (`features`, `bestFor`) are kept, because "Thumb
 * holes" or "Breathability" is a functional descriptor rather than anyone's
 * expression. Anything that reaches for brand heritage instead of function is
 * dropped — "Back from the Brooks vault" describes a company, not a garment.
 */
const HERITAGE = /\b(brooks|vault|throwback|retro|heritage|reissue|original|archive|anniversary|iconic|nostalgi)\w*/i;

function keepPhrase(s) {
  return typeof s === 'string' && s.trim() !== '' && !HERITAGE.test(s);
}

function main() {
  const catalog = JSON.parse(fs.readFileSync(CATALOG, 'utf8'));
  const stats = { products: 0, colorways: 0, images: 0, unmappedFranchise: new Set() };

  catalog.source = 'synthetic — generated by tools/debrand (no third-party data)';
  catalog.debrandedAt = new Date().toISOString();

  for (const p of catalog.products) {
    stats.products++;
    if (p.franchise && !FRANCHISE[p.franchise]) stats.unmappedFranchise.add(p.franchise);

    p.name = renameProduct(p.name, p.franchise);
    if (p.franchise) p.franchise = FRANCHISE[p.franchise] ?? p.franchise;
    if (Array.isArray(p.bestFor)) p.bestFor = p.bestFor.filter(keepPhrase).map(demark);
    if (Array.isArray(p.features)) p.features = p.features.filter(keepPhrase).map(demark);
    // Generated last: `describe` reads the already-renamed name and the
    // already-filtered attribute lists, so the copy never quotes what we just
    // removed. The harvested description is discarded outright.
    p.description = describe(p);

    // The product's own page on brooksrunning.com. Nothing in the demo should
    // deep-link to the real store, so the field becomes an in-app path.
    if (p.url) p.url = `/product/${p.id}`;

    if (Array.isArray(p.groups)) {
      p.groups = p.groups.map((g) => {
        for (const [from, to] of GROUP_SLUGS) if (g === from) return to;
        return g;
      });
    }

    for (const c of p.colors ?? []) {
      stats.colorways++;
      const { stops, name } = swatchFor(c.name, c.code);
      c.name = name;
      c.swatch = stops;
      // Keep one entry per original photo so the PDP gallery, its thumbnail
      // rail, and the pagination dots all keep their existing counts. The URI
      // carries the frame index so each frame can be composed differently.
      c.images = (c.images ?? []).map((_, i) => {
        stats.images++;
        return { url: `swatch:${stops.join(',')}#${i}`, alt: `${p.name} — ${name}` };
      });
    }
  }

  // Franchise values also appear as facet options.
  for (const f of catalog.facets ?? []) {
    for (const o of f.options ?? []) {
      if (typeof o.display_name === 'string') o.display_name = demark(o.display_name);
      if (typeof o.value === 'string' && FRANCHISE[o.value]) o.value = FRANCHISE[o.value];
    }
  }

  for (const cat of catalog.categories ?? []) {
    cat.id = GROUP_SLUGS.reduce((id, [from, to]) => (id === from ? to : id), cat.id);
    cat.label = demark(cat.label);
  }

  fs.writeFileSync(CATALOG, `${JSON.stringify(catalog, null, 0)}\n`);

  console.log(`products    ${stats.products}`);
  console.log(`colorways   ${stats.colorways}`);
  console.log(`images      ${stats.images}`);
  console.log(
    `unmapped    ${stats.unmappedFranchise.size ? [...stats.unmappedFranchise].join(', ') : 'none'}`,
  );
}

main();
