/**
 * Replaces the harvested TurnTo reviews with synthetic ones.
 *
 * 624 reviews written by 557 named members of the public are the clearest
 * third-party content in the app: real people's words under real people's
 * names. Ratings, dates, and the fit-dimension averages are kept, because
 * numbers make the review UI exercise its real layout and carry no one's
 * expression. Titles, bodies, and authors are generated.
 *
 * Usage: node tools/debrand/reviews.js
 * Reads/writes packages/catalog/reviews.json in place, then run `bun run sync`.
 */

const fs = require('fs');
const path = require('path');

const { hash, pick } = require('./copy.js');

const ROOT = path.resolve(__dirname, '../..');
// packages/catalog is the source of truth; `bun run sync` copies it into
// assets/ and src/data/. Editing the generated copy would be undone.
const REVIEWS = path.join(ROOT, 'packages/catalog/reviews.json');

/** Generic initials, so no synthetic author reads as a real person's name. */
const INITIALS = 'ABCDEFGHJKLMNPRSTVW'.split('');

/**
 * Bodies indexed by rating, so a 5-star review does not read like a complaint.
 * Short and plainly synthetic on purpose — this is demo furniture, not an
 * attempt to sound like a real review corpus.
 */
const BY_RATING = {
  5: [
    ['Exactly right', 'Fits as expected and feels good over longer distances. No complaints so far.'],
    ['Would buy again', 'Comfortable from the first wear. Holding up well after a few weeks.'],
    ['Great everyday pick', 'Light enough for daily use and the fit is consistent with my usual size.'],
  ],
  4: [
    ['Solid, minor niggles', 'Good overall. Took a couple of wears to break in, but comfortable now.'],
    ['Happy with it', 'Does what I wanted. The colour is slightly different to the swatch.'],
    ['Good value', 'Comfortable and well made. I would prefer a little more room in the toe.'],
  ],
  3: [
    ['Middle of the road', 'Fine, but nothing stood out. Fit was true to size.'],
    ['Mixed feelings', 'Comfortable enough, though not as supportive as I hoped.'],
    ['Okay for the price', 'Reasonable quality. I may size up next time.'],
  ],
  2: [
    ['Not for me', 'The fit was narrower than I expected and I could not get comfortable.'],
    ['Disappointing', 'Looked right but felt stiff. Ended up returning it.'],
  ],
  1: [
    ['Returned it', 'Wrong fit for me and uncomfortable from the start.'],
    ['Would not recommend', 'Did not work out. Sizing felt well off my usual.'],
  ],
};

/** Deterministic "First L." style author from the review id. */
function author(id) {
  const h = hash(`author:${id}`);
  const first = INITIALS[h % INITIALS.length];
  const last = INITIALS[(h >>> 8) % INITIALS.length];
  return `${first}. ${last}.`;
}

function main() {
  const data = JSON.parse(fs.readFileSync(REVIEWS, 'utf8'));
  let count = 0;

  data.source = 'synthetic — generated by tools/debrand (no third-party content)';
  data.debrandedAt = new Date().toISOString();

  for (const product of Object.values(data.products ?? {})) {
    for (const r of product.recent ?? []) {
      count++;
      // Clamp into the table's range; the harvest has only 1-5 but a
      // re-harvest should not be able to produce an undefined lookup.
      const band = Math.min(5, Math.max(1, Math.round(r.rating ?? 3)));
      const [title, text] = pick(BY_RATING[band], r.id, 'body');
      r.title = title;
      r.text = text;
      r.author = author(r.id);
      // "Staff" marked a Brooks employee review. Nothing in the demo has
      // staff, so the distinction is dropped rather than reassigned.
      r.badge = null;
    }
  }

  fs.writeFileSync(REVIEWS, `${JSON.stringify(data, null, 0)}\n`);
  console.log(`reviews     ${count}`);
}

main();
